spring.application.name=Climalert

# ===============================
# BASE DE DATOS (H2 en memoria)
# ===============================
spring.datasource.url=jdbc:h2:mem:climalertdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=
# Habilita la consola web de H2 en http://localhost:8080/h2-console
# Todavia no logre que se vea pero si se consulta por SQL en ejecucion muestra los datos guardados
# TODO
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# ===============================
# WEATHER API
# ===============================
# Aquí va la API de WeatherAPI, la mia la tengo en archivo de propiedades locales
weather.api.key=null
# Endpoint específico
weather.api.url=http://api.weatherapi.com/v1/current.json
# Ubicación fija a consultar
weather.api.location=CABA

# ===============================
# CORREO ELECTRÓNICO (SMTP)
# ===============================
# Configuración genérica de prueba usando mailtrap.io, password en archivo de propiedades locales
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=906609e865f1e8
spring.mail.password=null
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true